[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

[dev]
  command = "npm run dev:all"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://swift-invoice-vde7.onrender.com"
  VITE_FIREBASE_API_KEY = "AIzaSyCO31KE_hEFAwXJ127EpW3-4olv2LduBus"
  VITE_FIREBASE_AUTH_DOMAIN = "swift-invoi.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "swift-invoi"
  VITE_FIREBASE_STORAGE_BUCKET = "swift-invoi.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "82621252142"
  VITE_FIREBASE_APP_ID = "1:82621252142:web:9210f3e515f29fd35255bf"
  VITE_FIREBASE_MEASUREMENT_ID = "G-4KLD1D7EP5"

[context.deploy-preview.environment]
  VITE_API_URL = "https://swift-invoice-vde7.onrender.com"
  VITE_FIREBASE_API_KEY = "AIzaSyCO31KE_hEFAwXJ127EpW3-4olv2LduBus"
  VITE_FIREBASE_AUTH_DOMAIN = "swift-invoi.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "swift-invoi"
  VITE_FIREBASE_STORAGE_BUCKET = "swift-invoi.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "82621252142"
  VITE_FIREBASE_APP_ID = "1:82621252142:web:9210f3e515f29fd35255bf"
  VITE_FIREBASE_MEASUREMENT_ID = "G-4KLD1D7EP5"

